switch (global.option_difficulty_level) {
    case global.difficulty_level_easy:
        global.counter_create_enemy_limit = 10
        global.TOTAL_SHIPS_1 = 3
        global.TOTAL_SHIPS_2 = 2
        global.TOTAL_SHIPS_3 = 3
        global.TOTAL_SHIPS_4 = 2
        global.TOTAL_SHIPS_5 = 3
        global.TOTAL_SHIPS_6 = 4
        global.TOTAL_SHIPS_7 = 1
        global.TOTAL_SHIPS_8 = 4
        global.TOTAL_SHIPS_9 = 2
        global.TOTAL_SHIPS_10 = 1
        global.TOTAL_SHIPS_11 = 2
        global.TOTAL_SHIPS_12 = 3
        global.TOTAL_SHIPS_13 = 3
        global.TOTAL_SHIPS_14 = 1
        global.TOTAL_SHIPS_15 = 1
        global.TOTAL_SHIPS_16 = 3
        global.TOTAL_MONSTERS_1 = 3 
        global.TOTAL_MONSTERS_2 = 3
        global.TOTAL_MONSTERS_3 = 3
        global.TOTAL_MONSTERS_4 = 1
        global.TOTAL_MONSTERS_6 = 4
        global.TOTAL_BOMBS = 5
        global.TOTAL_ALIEN = 8
        global.TOTAL_TANK_1 = 2
        global.TOTAL_METEORS= 0
        global.BOSS_1_HP_MAX = 600
        global.TOTAL_ENEMY_ARMORED_DRONE = 2
        break
    case global.difficulty_level_normal:    
        global.counter_create_enemy_limit = 10
        global.TOTAL_SHIPS_1 = 4
        global.TOTAL_SHIPS_2 = 2
        global.TOTAL_SHIPS_3 = 3
        global.TOTAL_SHIPS_4 = 3
        global.TOTAL_SHIPS_5 = 3
        global.TOTAL_SHIPS_6 = 5
        global.TOTAL_SHIPS_7 = 2
        global.TOTAL_SHIPS_8 = 6
        global.TOTAL_SHIPS_9 = 4
        global.TOTAL_SHIPS_10 = 2
        global.TOTAL_SHIPS_11 = 4
        global.TOTAL_SHIPS_12 = 4
        global.TOTAL_SHIPS_13 = 4
        global.TOTAL_SHIPS_14 = 1
        global.TOTAL_SHIPS_15 = 1        
        global.TOTAL_SHIPS_16 = 6
        global.TOTAL_MONSTERS_1 = 5 
        global.TOTAL_MONSTERS_2 = 5
        global.TOTAL_MONSTERS_3 = 5
        global.TOTAL_MONSTERS_4 = 2
        global.TOTAL_MONSTERS_6 = 6
        global.TOTAL_BOMBS = 8
        global.TOTAL_ALIEN = 10
        global.TOTAL_TANK_1 = 4        
        global.BOSS_1_HP_MAX = 800
        global.TOTAL_ENEMY_ARMORED_DRONE = 4
        break
   case global.difficulty_level_hard:    
        global.counter_create_enemy_limit = 10
        global.TOTAL_SHIPS_1 = 6
        global.TOTAL_SHIPS_2 = 2
        global.TOTAL_SHIPS_3 = 6
        global.TOTAL_SHIPS_4 = 5
        global.TOTAL_SHIPS_5 = 5
        global.TOTAL_SHIPS_6 = 8
        global.TOTAL_SHIPS_7 = 3
        global.TOTAL_SHIPS_8 = 8
        global.TOTAL_SHIPS_9 = 6    
        global.TOTAL_SHIPS_10 = 4   
        global.TOTAL_SHIPS_11 = 6   
        global.TOTAL_SHIPS_12 = 6      
        global.TOTAL_SHIPS_13 = 6
        global.TOTAL_SHIPS_14 = 1
        global.TOTAL_SHIPS_15 = 1        
        global.TOTAL_SHIPS_16 = 9
        global.TOTAL_MONSTERS_1 = 7 
        global.TOTAL_MONSTERS_2 = 7
        global.TOTAL_MONSTERS_3 = 7
        global.TOTAL_MONSTERS_4 = 3
        global.TOTAL_MONSTERS_6 = 8
        global.TOTAL_BOMBS = 10
        global.TOTAL_ALIEN = 15
        global.TOTAL_TANK_1 = 6    
        global.TOTAL_METEORS= 3
        global.BOSS_1_HP_MAX = 1000
        global.TOTAL_ENEMY_ARMORED_DRONE = 5
        break
}
